"""initial schema

Revision ID: 7474282d0d4f
Revises:
Create Date: 2026-07-25 11:13:33.229677
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7474282d0d4f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("connector_type", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("config_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("config_ref", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("health_status", sa.String(), nullable=False),
        sa.Column("health_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "health_status IN ('unknown', 'healthy', 'unhealthy')",
            name=op.f("ck_connections_valid_health_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connections")),
    )
    op.create_table(
        "evaluation_cases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_cases")),
        sa.UniqueConstraint("name", "version", name="uq_evaluation_case_version"),
    )
    op.create_table(
        "evidence_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("source_tier", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("context_version", sa.String(), nullable=False),
        sa.Column("freshness_status", sa.String(), nullable=False),
        sa.Column("max_data_date", sa.String(), nullable=True),
        sa.Column("sql_ref", sa.String(), nullable=True),
        sa.Column("result_ref", sa.String(), nullable=True),
        sa.Column("skill_version", sa.String(), nullable=True),
        sa.Column("analysis_ref", sa.String(), nullable=True),
        sa.Column("trace_ref", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("metrics_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("datasets_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("business_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unresolved_ambiguity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_state", sa.String(), nullable=False),
        sa.Column("fallback", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("missing_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_records")),
    )
    op.create_table(
        "governed_context",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("context_type", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("current_version_id", sa.String(), nullable=True),
        sa.Column("lifecycle", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle IN ('candidate', 'in_review', 'approved', 'deprecated')",
            name=op.f("ck_governed_context_valid_lifecycle"),
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["governed_context_versions.id"],
            name="fk_gc_current_version",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_governed_context")),
        sa.UniqueConstraint("context_type", "domain", "name", name="uq_governed_context_identity"),
    )
    op.create_index(
        "ix_governed_context_domain_type",
        "governed_context",
        ["domain", "context_type"],
        unique=False,
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scorecard", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("context_versions_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["evaluation_cases.id"],
            name=op.f("fk_evaluation_runs_case_id_evaluation_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_table(
        "governed_context_versions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("context_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_assets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("joins", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("freshness_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation_guidance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conflicts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deprecations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewer", sa.String(), nullable=True),
        sa.Column("approval_decision_id", sa.String(), nullable=True),
        sa.Column("review_interval_days", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_decision_id"],
            ["review_decisions.id"],
            name="fk_gcv_approval_decision",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["governed_context.id"],
            name=op.f("fk_governed_context_versions_context_id_governed_context"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_governed_context_versions")),
        sa.UniqueConstraint("context_id", "version", name="uq_context_version"),
    )
    op.create_index(
        "ix_governed_context_versions_search",
        "governed_context_versions",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "observed_assets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("connection_id", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("asset_type", sa.String(), nullable=False),
        sa.Column("current_version_id", sa.String(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_observed_assets_connection_id_connections"),
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["observed_asset_versions.id"],
            name="fk_oa_current_version",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observed_assets")),
        sa.UniqueConstraint("connection_id", "external_id", "asset_type", name="uq_asset_identity"),
    )
    op.create_index("ix_observed_assets_type", "observed_assets", ["asset_type"], unique=False)
    op.create_table(
        "review_tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("affected_asset_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("affected_context_id", sa.String(), nullable=True),
        sa.Column("proposal_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processor_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluation_impact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("assignee", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'resolved', 'dismissed')",
            name=op.f("ck_review_tasks_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["affected_context_id"],
            ["governed_context.id"],
            name=op.f("fk_review_tasks_affected_context_id_governed_context"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_tasks")),
        sa.UniqueConstraint("idempotency_key", name="uq_review_task_idempotency_key"),
    )
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("connection_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "mode IN ('full', 'incremental', 'fixture_import')",
            name=op.f("ck_sync_runs_valid_mode"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')", name=op.f("ck_sync_runs_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_sync_runs_connection_id_connections"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    op.create_index(
        "ix_sync_runs_connection_started",
        "sync_runs",
        ["connection_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "asset_relationships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("from_asset_id", sa.String(), nullable=False),
        sa.Column("to_asset_id", sa.String(), nullable=False),
        sa.Column("relation", sa.String(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_asset_id"],
            ["observed_assets.id"],
            name=op.f("fk_asset_relationships_from_asset_id_observed_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["to_asset_id"],
            ["observed_assets.id"],
            name=op.f("fk_asset_relationships_to_asset_id_observed_assets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_relationships")),
    )
    op.create_table(
        "connector_checkpoints",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("connection_id", sa.String(), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_sync_run_id", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            name=op.f("fk_connector_checkpoints_connection_id_connections"),
        ),
        sa.ForeignKeyConstraint(
            ["last_sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_connector_checkpoints_last_sync_run_id_sync_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_checkpoints")),
        sa.UniqueConstraint("connection_id", name=op.f("uq_connector_checkpoints_connection_id")),
    )
    op.create_table(
        "context_asset_links",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("context_version_id", sa.String(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("relation", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["observed_assets.id"],
            name=op.f("fk_context_asset_links_asset_id_observed_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["context_version_id"],
            ["governed_context_versions.id"],
            name=op.f("fk_context_asset_links_context_version_id_governed_context_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_asset_links")),
    )
    op.create_table(
        "observed_asset_versions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("sync_run_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["observed_assets.id"],
            name=op.f("fk_observed_asset_versions_asset_id_observed_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_observed_asset_versions_sync_run_id_sync_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observed_asset_versions")),
        sa.UniqueConstraint("asset_id", "version", name="uq_asset_version"),
    )
    op.create_index(
        "ix_observed_asset_versions_search",
        "observed_asset_versions",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("review_task_id", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("decided_by", sa.String(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resulting_context_version_id", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "decision IN ('approve', 'edit', 'reject')",
            name=op.f("ck_review_decisions_valid_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["resulting_context_version_id"],
            ["governed_context_versions.id"],
            name=op.f("fk_review_decisions_resulting_context_version_id_governed_context_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["review_task_id"],
            ["review_tasks.id"],
            name=op.f("fk_review_decisions_review_task_id_review_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_decisions")
    op.drop_index(
        "ix_observed_asset_versions_search",
        table_name="observed_asset_versions",
        postgresql_using="gin",
    )
    op.drop_table("observed_asset_versions")
    op.drop_table("context_asset_links")
    op.drop_table("connector_checkpoints")
    op.drop_table("asset_relationships")
    op.drop_index("ix_sync_runs_connection_started", table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_table("review_tasks")
    op.drop_index("ix_observed_assets_type", table_name="observed_assets")
    op.drop_table("observed_assets")
    op.drop_index(
        "ix_governed_context_versions_search",
        table_name="governed_context_versions",
        postgresql_using="gin",
    )
    op.drop_table("governed_context_versions")
    op.drop_table("evaluation_runs")
    op.drop_index("ix_governed_context_domain_type", table_name="governed_context")
    op.drop_table("governed_context")
    op.drop_table("evidence_records")
    op.drop_table("evaluation_cases")
    op.drop_table("connections")
    # ### end Alembic commands ###
